name: Decode GitHub secrets
description: Decode and setup google-services.json, local.properties, and ~/.android/release.keystore

runs:
  using: "composite"
  steps:
    - name: Decode google-services.json from secrets
      env:
        GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
      shell: bash
      run: |
        if [ -n "$GOOGLE_SERVICES" ]; then
          echo "$GOOGLE_SERVICES" | base64 --decode > ./app/google-services.json
        else
          echo "::warning::GOOGLE_SERVICES secret is not set. google-services.json will not be created."
        fi

    - name: Decode local.properties from secrets
      env:
        LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
      shell: bash
      run: |
        if [ -n "$LOCAL_PROPERTIES" ]; then
          echo "$LOCAL_PROPERTIES" | base64 --decode > ./local.properties
        else
          echo "::warning::LOCAL_PROPERTIES secret is not set. local.properties will not be created."
        fi

    - name: Decode release keystore from secrets
      env:
        ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      shell: bash
      run: |
        if [ -n "$ANDROID_KEYSTORE_BASE64" ]; then
          mkdir -p ~/.android
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > ~/.android/release.keystore
        else
          echo "::warning::ANDROID_KEYSTORE_BASE64 secret is not set. ~/.android/release.keystore will not be created."
        fi

