name: 'Decode Secrets'
description: 'Decode and setup Google Services and Local Properties files'

inputs:
  google-services:
    description: 'Base64 encoded Google Services JSON'
    required: false
  local-properties:
    description: 'Base64 encoded Local Properties file'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Decode secrets
      shell: bash
      env:
        GOOGLE_SERVICES: ${{ inputs.google-services }}
        LOCAL_PROPERTIES: ${{ inputs.local-properties }}
      run: |
        if [ -n "$GOOGLE_SERVICES" ]; then
          echo "$GOOGLE_SERVICES" | base64 --decode > ./app/google-services.json
        else
          echo "::warning::GOOGLE_SERVICES secret is not set. google-services.json will not be created."
        fi

        if [ -n "$LOCAL_PROPERTIES" ]; then
          echo "$LOCAL_PROPERTIES" | base64 --decode > ./local.properties
        else
          echo "::warning::LOCAL_PROPERTIES secret is not set. local.properties will not be created."
        fi
